Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Niocle Santos da Silveira e Marcos Paulo dos Santos araujo
// Data atual  : 01/04/2021
Var
// Seção de Declarações das variáveis 
Algoritmo "numeros"
x: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para x de 1 ate 10 faca
 escreval(x)
fimpara

Fimalgoritmo